/*++

    toro C Library
    https://github.com/KilianKegel/toro-C-Library#toro-c-library-formerly-known-as-torito-c-library

    Copyright (c) 2017-2025, Kilian Kegel. All rights reserved.
    SPDX-License-Identifier: GNU General Public License v3.0

Module Name:

    PreBuild.c

Abstract:

    toro C Library build tool

Author:

    Kilian Kegel

--*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

char szCopyBuf[2048];
char szCopyBuG[2048];
char szCopy[] = { "\nToro C Library for IBM PC AT(tm) compatible %s UEFI shell and Windows NT executables\nCopyright (c) %d, Kilian Kegel, https://github.com/KilianKegel/toro-C-Library\nBuild %s\n\nPermission to use Torito C Library for the SOLE PURPOSE OF ANYTHING by creating\nUEFI Shell applications, which may be\ndistributed with or without fee, is hereby granted, provided that the above\ncopyright notice and this permission notice appear in all binary copies\nand during startup of the application itself when invoked with dedicated\ncommand line arguments (/h and /?).\n\nIt is not allowed to sell Torito C Library as a stand alone product or\nto modify it's content in any way.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH\nREGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND\nFITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL,DIRECT,INDIRECT,\nOR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,\nDATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS\nACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS\nSOFTWARE.\n\n" };

typedef struct {
    int len;
    char* name;
    char* string;
}STRINGS;

int main(int argc, char** argv) {
    time_t timer = time(NULL);
    struct tm* time = gmtime(&timer);
    char szTimeStamp[32];
    char szBuildDate[32];
    char szBuild[64];
    char szCommit[64] = { "8a718ce" };
    char* pCommitSHA;

    if (0) {//debug
        volatile int x = 0; while (0 == x);
    }

    sprintf(szTimeStamp, "%02d%02d%02d%02d%02d%02d", (time->tm_year + 1900) % 100, time->tm_mon + 1, time->tm_mday, time->tm_hour, time->tm_min, time->tm_sec);
    sprintf(szBuildDate, "%04d%02d%02d", (time->tm_year + 1900) , time->tm_mon + 1, time->tm_mday);
    //
    // try to extract commit SHA from the $(SolutionDir), parameter argv[1]
    //
    pCommitSHA = strrchr(argv[1], '.');
    while (*++pCommitSHA != '\\')
    {
        static int i = 0;
        szCommit[i++] = *pCommitSHA;
        szCommit[i] = '\0';
    }

    sprintf(szBuild, "%s/%s", szBuildDate, szCommit);
    sprintf(szCopyBuf, szCopy, sizeof(void*) == 8 ? "x86-64" : "x86-32", (time->tm_year + 1900), szBuild);

    if (1) {
        //
        // generate "LibAssistant\\_gCdeCopyright.c"
        //
        FILE* fp = NULL;
        int ii = 0;
        char szProjectDir[128];

        strcpy(szProjectDir, argv[2]);
        strcat(&szProjectDir[strlen(szProjectDir)], "LibAssist\\_gCdeCopyright.c");
        
        fp = fopen(szProjectDir, "w");

        fprintf(fp, "//\n//this file is automatically generated at build time\n//\n");

        fprintf(fp, "//#include <CdeStealth.h>\nchar _gCdeCopyRight[]={\n");

        for (ii = 0; ii < strlen(szCopyBuf); ii++)
            fprintf(fp, "%s0x%02X,%s", 0 == (ii % 16) ? "\t\t" : "", szCopyBuf[ii], 0 == ((ii + 1) % 16) ? "\\\n" : "");

        fprintf(fp, "%s\n\t0,0};\n", ii % 16 ? "\\" : "");

        fprintf(fp, "/*");//next line
        for (ii = 0; ii < strlen(szCopyBuf); ii++)
            fprintf(fp, "%c", szCopyBuf[ii]);
        fprintf(fp, "*/");

        fclose(fp);


    }

    if (1) {
        //
        // generate "include\\CdeLicense.h"
        //
        FILE* fp = NULL;
        int ii = 0, i, j, k, overall;
        char szProjectDir[128];
        int BUILDYEA = time->tm_year + 1900;
        int BUILDMON = time->tm_mon + 1;
        int BUILDDAY = time->tm_mday;
        int BUILDHOU = time->tm_hour;
        int BUILDMIN = time->tm_min;
        int BUILDSEC = time->tm_sec;
        int fRELEASE = !strcmp("Release", argv[3]);
        int fARCH64 = sizeof(void*) == 8;
        char* p;

        strcpy(szProjectDir, argv[2]);
        strcat(&szProjectDir[strlen(szProjectDir)], "include\\CdeLicense.h");

        fp = fopen(szProjectDir, "w");

        fprintf(fp, "//\n//this file is automatically generated at build time\n//\n");
        fclose(fp);


    }


    return 0;
}